---
title: "CRM_DMS_2014_Gvis"
output: html_document


---

# Vorgehen für Entwicklung:

# Auch für die Market-Units die Region mit nehmen - um sie als Color-Variable aufzunehmen: colorvar="Region",

# um in der Anzeige bis zum Schluss alle Länder anzuzeigen:
#    * falls es kein Datum zum 31.12. gibt:
#        - pro Market-Unit, einen Eintrag mit Value 0 generieren (Nachteil: dies erhöht die Anzal der Oppis um 1)
#        - Verändern der letzen Datums auf den 31.12. (Nachteil: letzte Oppi wird nicht korrekt angezeigt) 
#    * ausserdem: selektieren aller Oppis nur für 2014 (sonst kriegt man kein höchstes  End-Datum hin)
#

# Design-Überlegungen:
# Aufbau einer Tabelle mit dem Schlüssel: Market-Unit und Datum, dann die folgenden Werte Spaltenweise ablegen
# Region (kann man als Farbvariable gebrauchen)
# status
# Value_Won (Wert der gewonnen Projekte)
# Number_Won (Anzahl der gewonnen Projekte)
# Value_Lost (Wert der verlorenen Projekte)
# Number_Lost (Anzahl der verlorenen Projekte)
# noch offen: analog für Oppis in Process - Schwierigkeit hier: fehlen des Enddatums:
# statt Enddatum muss man alle Oppis aufsummieren, die bis zu dem Datum offen sind.

# Sortierung der Tabelle nach:
# Market-Unit
# Datum

# Diese Tabelle wird aufgebaut über einen Loop über die ursprüngliche Tabelle:

library(googleVis)
library(reshape)
setwd('~/Downloads')
dms_crm_org <- read.csv('CRM_dms_7_1.txt', sep = '\t') 


library(plyr) 
#Vorsicht: falls man auch das dpylr Paket installiert hat, so muss man dieses erst deinstallieren!
#für rename braucht man das plyr-package

dms_crm <- plyr::rename(dms_crm_org, c(OPP.Status="Status", Unweighted.After.Split.Rev.Plus.Trav.EURO.BC = "Value", Global.LoS.Prod.Hier.L4="Product", Service.Product = "Service", End.Customer.SAP.MC.Customer="Cust.Cat"))

library(dplyr)
dms_crm <- select(dms_crm, Region, OPP.ID, Status, Value, Market.Unit, Product, Service, Closing.Yr, Cust.Cat, Closing.Dt, Creation.Dt, Creation.Yr.Mon)

# unsinnige Regionen wegselektieren:

dms_crm <- subset(dms_crm, Region != "ARIBA (CLOUD SRM)" & Region != "CORPORATE" & Region != "GREATER CHINA" )

cond <- dms_crm$Status == 'In process'
dms_crm$status <- ifelse(cond, 'In process', NA)

cond <- dms_crm$Status == 'Booked'| dms_crm$Status == 'Won'
dms_crm$status <- ifelse(cond, 'Won', dms_crm$status)

cond <- dms_crm$Status == 'Discontinued'| dms_crm$Status == 'Lost'
dms_crm$status <- ifelse(cond, 'Lost', dms_crm$status)

# umwandeln der Datums-Felder, damit sie als Datum von R erkannt werden:

dms_crm$Closing.Dt <- as.Date(dms_crm$Closing.Dt, format='%m/%d/%y %H:%M')
dms_crm$Creation.Dt <- as.Date(dms_crm$Creation.Dt, format='%m/%d/%y %H:%M')

# mit dem folgenden Verfahren schließt man 24 Oppis aus 2015 aus:

# falls Opportunities ein Closing.Dt in 2015 haben, wird dieses auf den 31.12.2014 gesetzt - wenn man dies nicht macht, "fransen" die Darstellungen für 2015 aus.
# vorher werden noch die Opportunities die nicht "In process" sind und für 2015 ein Closing-Date haben, ausgeschlossen - damit man nur Daten aus 2014 sieht.

dms_crm <- subset(dms_crm, status == "In process" | Closing.Dt < "2015-01-01")

for (i in 1:nrow(dms_crm))
    if (dms_crm$Closing.Dt[i] >= as.Date("2015-01-01")){
    dms_crm$Closing.Dt[i] <- as.Date("2014-12-31")
    }
    

# statt das Endatum der Oppis auf 2014 zu setzen, könnte man diese auch wegselektieren, wie folgt - dann hätte man aber keine Übersicht mehr über die In-Process-Oppis:
#dms_crm <- subset(dms_crm, Closing.Dt < "2015-01-01")


#  die Tabelle noch mal sortieren nach Closing Date
attach(dms_crm)
 
dms_crm_sort <- dms_crm[order(Closing.Dt),]
detach(dms_crm)

dms_crm <- dms_crm_sort

# eine Zählvariable einführen, die von Plyr mitgezählt wird, damit man auch über die Anzahl der Oppis auswerten kann:

dms_crm$number <- 1

# um Eindeutigkeit bzgl. Market.Unit. Creation Date und Status zu erzielen, wendet man Plyr an:


dms_crm <- ddply(dms_crm, .(Region, Market.Unit, status, Closing.Dt), summarize,  number = sum(number), Value = sum(Value))

# überführen der Daten in ein Wide Format:

dms_wide <- reshape(dms_crm, idvar = c("Market.Unit","Closing.Dt"), v.names = c("Value", "number"), timevar = "status", direction = "wide")

# ersetzen der NA-Werte durch 0:
dms_wide[is.na(dms_wide)] <- 0

# noch mal sortieren:
attach(dms_wide)
 
dms_wide_sort <- dms_wide[order(Region, Market.Unit, Closing.Dt),]
detach(dms_wide)

dms_wide <- dms_wide_sort
# nun erfolgt das aufsummieren über die Daten entlang der Zeitachse:

for (i in 2:nrow(dms_wide))
   if (dms_wide$Market.Unit[i] == dms_wide$Market.Unit[i-1]){
      dms_wide$number.Won[i] <- dms_wide$number.Won[i] + dms_wide$number.Won[i-1]
      dms_wide$Value.Won[i] <- dms_wide$Value.Won[i]  + dms_wide$Value.Won[i-1]  
      dms_wide$number.Lost[i] <-  dms_wide$number.Lost[i] + dms_wide$number.Lost[i-1]
      dms_wide$Value.Lost[i] <- dms_wide$Value.Lost[i] + dms_wide$Value.Lost[i-1]  
      dms_wide$number.In.process[i] <-  dms_wide$number.In.process[i] + dms_wide$number.In.process[i-1]
      dms_wide$Value.In.process[i] <- dms_wide$Value.In.process[i] + dms_wide$Value.In.process[i-1] 
    } 



# mit den myStateSettings, kann man die Start-Werte vorgegeben - man kannn das auch weg lassen und braucht das nciht zu verstehen. 

myStateSettings <- '
{"colorOption":"2","yLambda":1,"time":"2014-12-01","xZoomedDataMax":378,"xLambda":1,"yAxisOption":"7","xZoomedIn":false,"yZoomedDataMax":28764388,"yZoomedDataMin":0,"iconType":"BUBBLE","yZoomedIn":false,"orderedByY":false,"uniColorForNonSelected":false,"sizeOption":"5","xZoomedDataMin":0,"iconKeySettings":[],"orderedByX":false,"nonSelectedAlpha":0.4,"showTrails":true,"dimensions":{"iconDimensions":["dim0"]},"playDuration":15000,"xAxisOption":"8","duration":{"multiplier":1,"timeUnit":"D"}}
'



M <- gvisMotionChart(dms_wide,
                    idvar="Market.Unit",
                    timevar="Closing.Dt",
                    options=list(state=myStateSettings))
                 
                    
plot(M)


print(M, file="CRM_dms_2014_v2.html")


